### ISSUE TITLE
Upgrade to Karate 1.1.0

### ISSUE THREAD

**Issue by fkjellberg** [reMarkable/docker-karate#1]
Are there any plans to upgrade to the latest Karate version and switch to a more lightweight alpine based java image?

**Comment by hedlund** [comment]
Sorry, this is not an image that's actively used, so chances are small we'll update it.. We probably should deprecate the repository to clarify it's not actively maintained..

**Comment by fkjellberg** [comment]
I understand. Would you mind if I copy the code from this repository and create my own image and possibly publish it? I cannot find an explicit license in this repo?

**Comment by hedlund** [comment]
@fkjellberg Of course, go ahead and copy it. 😄 👍 

There's hardly antyhing "copyrightable" in this repo after all, which is probably why I didn't bother with a license..  🙂

**Comment by fkjellberg** [comment]
@hedlund Thank you!
